#!/bin/sh
rsync -av ./ u97288435@access783107477.webspace-data.io:~/sniw --include=config --include=vendor/coresphere --include=public/build --include=public/styles --include=public/.htaccess --exclude=public/produits/images --exclude-from=.gitignore --exclude=".*"
