#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_logout:
    path: /logout

mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

coresphere_console:
    resource: .
    type: extra

console:
    path:  /admin/_console
    defaults: { _controller: coresphere_console.controller:consoleAction }
    methods: [GET]

console_exec:
    path:  /admin/_console/commands.{_format}
    defaults: { _controller: coresphere_console.controller:execAction, _format: json }
    methods: [POST]
    requirements:
        _format: json
