# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'fr'
    app.category.form.type.class: App\Form\CategoryType
    upload_directory: '%kernel.project_dir%/public/file_produits'
    images_directory: '%kernel.project_dir%/public/produits/images'
    images_import_directory: '%kernel.project_dir%/public/file_images'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    console_command.csv_import:
          class: App\Import\ImportProduit
          arguments:
            - "@doctrine.orm.entity_manager"
          tags:
            - { name : console.command }

    console_command.csv_importclient:
          class: App\Import\ImportClient
          arguments:
            - "@doctrine.orm.entity_manager"
          tags:
            - { name : console.command }


    console_command.csv_importgroupe:
          class: App\Import\ImportGroupe
          arguments:
            - "@doctrine.orm.entity_manager"
          tags:
            - { name : console.command }


    console_command.csv_importgroupe_user:
          class: App\Import\ImportGroupe_User
          arguments:
            - "@doctrine.orm.entity_manager"
          tags:
            - { name : console.command }

    console_command.csv_import_manu:
          class: App\Import\ImportManufacturer
          arguments:
            - "@doctrine.orm.entity_manager"
          tags:
            - { name : console.command }

    console_command.csv_import_categorie:
          class: App\Import\ImportCategorie
          arguments:
            - "@doctrine.orm.entity_manager"
          tags:
            - { name : console.command }

    console_command.csv_importproduit_categorie:
          class: App\Import\ImportProduitCategorie
          arguments:
            - "@doctrine.orm.entity_manager"
          tags:
            - { name : console.command }

    console_command.csv_importproduit_image:
              class: App\Import\ImportProduitImage
              arguments:
                - "@doctrine.orm.entity_manager"
              tags:
                - { name : console.command }

    console_command.csv_importcommande:
              class: App\Import\ImportCommande
              arguments:
                - "@doctrine.orm.entity_manager"
              tags:
                - { name : console.command }

    app.form.type.about_users:
        class: App\Form\CategoryType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    App\Service\FileUploader:
            arguments:
                $targetDirectory: '%images_directory%'